version: '3'
services:
  server:
    image: node:16.14.2
    working_dir: /code
    ports: 
      - 3000:3000
    environment: 
      - DB_NAME=yayornay
      - DB_CONNECTION=mongodb://yayornay-admin:yayornay-password@db:27017
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm start"

  db:
    image: mongo:latest
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=yayornay-admin
      - MONGO_INITDB_DATABASE=yayornay
      - MONGO_INITDB_ROOT_PASSWORD=yayornay-password
volumes:
  dbdata: